### ISSUE TITLE
Msg Publisher 

### ISSUE THREAD

**Issue by germal** [simonernst/semantic_map#1]
Hello Simone 

I've found your work looking for a way to create 3d points around yolact_ros detections , in order to overlap them in rtabmap map , as "box" markers
Your code publish the pointclouds of the detected targets as tf transformation , so seems to me that it creates its own map  using the "semantic detection" of yolact.
In my case this tf breaks the three  , because I have already rtabmap that publish the transformation map->odom.
Is there a way to modify the code to publish the semantic pointclouds as messages ?
I noticed in that you have commented out some lines that used msg

create custom message with 3D points of mask
mask_message = Mask_Coordinates()
mask_message.class_name = label_store[i]
mask_message.score = score_store[i]

So maybe you have developed another version of the code with msg ?
Thanks in advance for your help !
Regards
germal

**Comment by simonernst** [comment]
Hi, 

The messages can be found in this repo : [yolact_ros_msgs](https://github.com/simonernst/yolact_ros_msgs)

I didn't work on this project for a while and the project is not finished at all, so I cannot guarantee what's working or not.

Regards, 
Simon

**Comment by germal** [comment]
Hi Simon
Thank you very much , I will try to follow your comments in the code.it's a shame that you have left this project , seems to me a brilliant way to solve the problem in the semantic mapping in a light way too !
Regards
germal
